### PR TITLE
Remove fs-extra and use util.promisify when possible.

### PR DESCRIPTION
**Pull request by XhmikosR**
Tested this on Node.js >= 8.6 and works fine https://github.com/XhmikosR/asset-resolver/runs/286388461

Now, there's only one case we use Bluebird:

https://github.com/bezoerb/asset-resolver/blob/31d52099de649cce39b07735af72247e99214afe/index.js#L24-L29

Would be nice to fix this and remove bluebird completely from the dependencies.

@bezoerb feel free to push here

Refs #228

### CODE REVIEW

**Comment by bezoerb** [comment]
@XhmikosR i've added a fix but i need push rights to your repo ;)
`fatal: Authentication failed for 'https://github.com/XhmikosR/asset-resolver.git/'`

**Comment by XhmikosR** [comment]
You only have push rights to the PR's branch. If this doesn't work it might be a GitHub issue

**Comment by bezoerb** [comment]
Pushing to your repo seems not possible :/

**Comment by XhmikosR** [comment]
Weird, I definitely use this on my other repos and i can push just fine. Maybe just merge this then and you push after that on master?

**Comment by XhmikosR** [comment]
If you follow the instructions shown in each PR:

>You can also open this in GitHub Desktop or view command line instructions

you can just push to each PR's branch directly.

**Pull request merged**
