### PR TITLE
Remove `os.EOL` and just use `'\n'`

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by bezoerb** [comment]
Is this working on Windows?

**Comment by XhmikosR** [comment]
Well TBH I haven't triggered the error message. Happy to do it if you let me know how.

**Comment by bezoerb** [comment]
> Well TBH I haven't triggered the error message. Happy to do it if you let me know how.

I've added another testcase. You can `console.log` the error message in test.js line 107

**Comment by bezoerb** [comment]
And please rebase ;) ...

**Comment by XhmikosR** [comment]
Seems fine:

error

I'll do the same for 1.x :)

PS. do not do merges in the future; this results in conflicts. Rebasing is preferable :)

**Pull request merged**
